### ISSUE TITLE
whitespace is converted to &#160;

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool-website#10]
In the web editor when I type a whitespace around a marked word it is converterd to a string "\&\#160;" after checking the text. For example, in the test for English, type a whitespace after "of of", check text and it becomes: 

> Paste your own text here and click the 'Check Text' button. Click the colored phrases for details on potential errors. or use this text too see an few of of\&\#160; the problems that LanguageTool can detecd. What do you thinks of grammar checkers? Please not that they are not perfect.

**Comment by jaumeortola** [comment]
@danielnaber Are you aware of this problem? It is quite annoying. Is it related to some recent change?

**Comment by danielnaber** [comment]
It was probably introduced when fixing https://github.com/languagetool-org/languagetool/issues/274. I didn't have time yet to look at it closely.

**Comment by danielnaber** [comment]
This is fixed by undoing the latest change (and thus introducing a different problem again).
