### ISSUE TITLE
> is incorrectly escaped as &gt; in the online tool

### ISSUE THREAD

**Issue by xPaw** [languagetool-org/languagetool-website#15]
Language appears to be irrelevant, noticed this when I tried to spell check a sentence which contained `<div>`.

Checking `<>` results in `&lt;&amp;gt;` returned by the API, but should be `&lt;&gt;`, which means there's a double escape going on somewhere.

**Comment by danielnaber** [comment]
Also see this TODO: https://github.com/languagetool-org/languagetool-website/blob/master/www/online-check/tiny_mce/plugins/atd-tinymce/src/atd.core.js#L269

**Comment by xPaw** [comment]
Perhaps fixing the API to not double escape as `&amp;gt;` would fix that problem?

**Comment by danielnaber** [comment]
It's not an API issue, e.g. `https://languagetool.org:8081/?language=en-US&text=my+texd+%3C%3E` returns no over-escaping as far as I can see.

**Comment by xPaw** [comment]
The only called by the site does that though. https://languagetool.org/api/v1/

```xml
<?xml version="1.0" encoding="UTF-8"?>
<matches software="LanguageTool" version="3.4-SNAPSHOT" buildDate="2016-04-19 22:01">
<language shortname="en-US" name="English (US)"/>
<error fromy="2" fromx="1" toy="2" tox="4" ruleId="MORFOLOGIK_RULE_EN_US" msg="Possible spelling mistake found" shortmsg="Spelling mistake" replacements="Sgt#gt#hgt" context="  &lt;&amp;gt;" contextoffset="3" offset="3" errorlength="3" category="Possible Typo" categoryid="TYPOS" locqualityissuetype="misspelling"/>
</matches>
```

**Comment by danielnaber** [comment]
Closing old issues, as this repo is not used anymore
