### ISSUE TITLE
Duplicated title element on new red button

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-website#33]
The new red button on the home page has a duplicated title element. In the HTML source, I see ` title="Check text - you can also use Ctrl+Return" title="Check your text by an expert"`.
Also, wouldn't "_Have_ your text checked by an expert" be more appropriate?

**Comment by danielnaber** [comment]
Thanks, fixed.

**Comment by jimdo-tiff** [comment]
@janschreiber Thanks for looking into it.
