### ISSUE TITLE
Small typo in source text

### ISSUE THREAD

**Issue by PanderMusubi** [languagetool-org/languagetool-website#37]
Please, replace this text with double single quotes

    We''ve checked your pattern against {0} sentences from the {1} Wikipedia and from Tatoeba found no matches. That''s a good sign, it means your rule doesn''t trigger any false alarms at least in the documents we checked.

with

    We've checked your pattern against {0} sentences from the {1} Wikipedia and from Tatoeba found no matches. That''s a good sign, it means your rule doesn't trigger any false alarms at least in the documents we checked.

**Comment by PanderMusubi** [comment]
And for

    We''ve checked your pattern against {0} sentences from the {1} Wikipedia and from Tatoeba and found the following matches. Please consider modifying your rule if these matches are false alarms. Hover over the words to display their part-of-speech tags.

and for

    This is a simple text check form. Use it as a fallback if the one on the LanguageTool homepage doesn''t work for you.

**Comment by PanderMusubi** [comment]
another one, `Ctrl+Return` is nowadays `Ctrl+Enter`, see also https://en.wikipedia.org/wiki/Enter_key

**Comment by PanderMusubi** [comment]
Hmmm, if the single double quotes is needed in the to be translated text, for character escaping reasons, should it also be used in the translated text as well?

**Comment by danielnaber** [comment]
> Hmmm, if the single double quotes is needed in the to be translated text, for character escaping reasons, should it also be used in the translated text as well?

Yes, please do that.

**Comment by PanderMusubi** [comment]
Examples of `don't` and other occurrences of `We've` are with only one single quote. In the Dutch translations, one doesn't use quotes in those places at all. So I recommended scanning the source .po files for two consecutive single quotes and fix those in the source code to in one single quote.

**Comment by danielnaber** [comment]
I guess this is fixed? If not, it belongs to https://github.com/languagetool-org/languagetool-community-website
