### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by amake** [languagetool-org/languagetool-website#38]
There doesn't seem to be a license associated with this repository. In particular I'm interested in using  [LT_circle.svg](https://github.com/languagetool-org/languagetool-website/blob/89e426d9006e1ecdc180a0a8a80a3bd1ca0b0a65/logo-sources/LT_circle.svg) as the basis for a macOS .app package icon, and would like to know if that would be permitted.

**Comment by danielnaber** [comment]
It's on https://languagetool.org/legal/: "The contents of this homepage is available under CC BY-SA 3.0." The logo is usually a special case, but feel free to use it.

**Comment by amake** [comment]
OK, thanks, I came straight to the repo so I missed that. Would you be open to adding a LICENSE file with CC BY-SA 3.0, as that is the license for the content? Or perhaps you would prefer LICENSE to point to the legal page since there is some content under other licenses?
