### ISSUE TITLE
iOS optimization

### ISSUE THREAD

**Issue by InnovativeInventor** [languagetool-org/languagetool-website#41]
I have a few ideas to improve the iOS mobile experience for the language tools website. Most of these ideas just turn a website into something that looks more like a native app on iOS.

- [ ] If a favicon named `apple-touch-icon.png` was added to the root folder, iOS will show it as the app icon when you press add to home screen on the homepage.

- [ ] Hide safari user interface components by adding `<meta name="apple-mobile-web-app-capable" content="yes">`

- [ ] Add a launch screen title for iOS by adding `<meta name="apple-mobile-web-app-title" content="LanguageTool">`

- [ ] Maybe create a special page just for iOS home apps by taking the homepage and removing everything except for the language tool

The ideas listed above only work when a webpage has been added to the safari home screen on iOS. [Here](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) is Apple's documentation on making websites look like apps.

**Comment by InnovativeInventor** [comment]
I added a page called web.php at my fork of this repository at [https://github.com/InnovativeInventor/languagetool-website](https://github.com/InnovativeInventor/languagetool-website) Would you like me to submit a pull request?

**Comment by danielnaber** [comment]
Closing old issues, as this repo is not used anymore
