### ISSUE TITLE
Incorrect correction

### ISSUE THREAD

**Issue by PanderMusubi** [languagetool-org/languagetool-website#42]
I had a text with the line:

    Blah blah blah eg. blah blah.

Which of course should be:

    Blah blah blah e.g. blah blah.

However, `e.g.` was not one of the options to choose in the website. so I added `e.g.`. This led unfortunately to the corrected sentence in the website of:

    Blah blah blah e.g.. blah blah.

Please, investigate and prevent `e.g..` getting added for this case.

**Comment by danielnaber** [comment]
Well, `eg` was marked, so if you add a replacement, that's exactly what will get replaced. I don't think we can add a special case to prevent the behavior you see.

**Comment by PanderMusubi** [comment]
The spell check also cannot handle it properly. Hopefully, one day, there might be support for these kind of errors but I understand the complexity here with the period `.` playing also a role in parsing.
