### ISSUE TITLE
Context menu with wrong offset (Firefox)

### ISSUE THREAD

**Issue by f-knorr** [languagetool-org/languagetool-website#43]
When using Firefox, i have the problem that the context menu of errors shows an unusual offset (see screenshot)
![unbenannt2](https://user-images.githubusercontent.com/16450958/34539750-26a6d2b8-f0d2-11e7-8b8e-28526db0fdfa.png)
I gets even worse after resizing the window: The context menu is now outside of the visible window area and i have to scroll to reach the context menu (I have added a red line which connects the context menu and the error to which it belongs)
![unbenannt](https://user-images.githubusercontent.com/16450958/34539795-5927b0b8-f0d2-11e7-94b0-6f983e32f4a1.png)
I use Firefix version 57.

**Comment by danielnaber** [comment]
Interesting, I cannot reproduce this. Which OS is this? What browser window size do you use? Is this a new issue?

**Comment by f-knorr** [comment]
I have investigated the problem a little further: It seems to be caused by the interaction with another add-on (StumbleBar by StumbleUpon).
So, I close this issue.
