### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [languagetool-org/languagetool-website#46]
The official websites are inaccessible for people restricted to IPv6-only connections. :(

**Comment by danielnaber** [comment]
May I ask how you noticed this? What kind of network are you on?

**Comment by tambry** [comment]
@danielnaber I'm occasionally restricted to IPv6-only connectivity. When my browser shows me on such occasions "This website is not available", then the cause is usually the lack of IPv6 support, and I can easily confirm that with a simple DNS query.

**Comment by danielnaber** [comment]
Please try again, it should be okay now.

**Comment by tambry** [comment]
It does indeed work now for languagetool.org! 😄  
Except for subscribing to the e-mail:

![2018-03-14_18-57-15_chrome](https://user-images.githubusercontent.com/1827708/37417680-93bdc802-27b9-11e8-8a4a-8a2673d31032.png)

Here's a table of IPv4-only hosts, that languagetool.org tries to load resources from:

|               Host              |       IP      |
|:-------------------------------:|:-------------:|
| api.newsletter2go.com           | 88.99.90.166  |
| d1f8f9xcsvx3ha.cloudfront.net   | 52.85.177.55  |
| languagetooler.onfastspring.com | 54.88.125.133 |
| static.newsletter2go.com        | 88.99.90.166  |
| www.newsletter2go.com           | 46.4.98.148   |

Cloudfront has good IPv6 support, so at least fixing that should be fairly easy.

[LanguageTool Plus](languagetoolplus.com) and [LanguageTool Forum](forum.languagetool.org) are also inaccessible over IPv6.  
Thank you for looking into this!

**Comment by danielnaber** [comment]
Well, these are external services, I don't see how I can fix their services without contacting them one by one. Fastspring surely has more users than LT, so this seems to indicate that ip6-only isn't a real issue yet.

**Comment by tambry** [comment]
But surely you can fix LanguageTool Plus and the LanguageTool Forum?

**Comment by danielnaber** [comment]
Closing old issues, as this repo is not used anymore
