### ISSUE TITLE
Links to API documentation are dead

### ISSUE THREAD

**Issue by crater2150** [languagetool-org/languagetool-website#47]
The links to the Javadoc API documentation point to missing pages.
On the [development page](https://languagetool.org/development), the link points to https://languagetool.org/api, while the one on the [Java API wiki page](http://wiki.languagetool.org/java-api) points to https://languagetool.org/development/api, which both result in a 404 error.

**Comment by danielnaber** [comment]
Thanks, all links should be fixed now.
