### ISSUE TITLE
Text checking box in homepage unusable (maybe due to a Javascript syntax error)

### ISSUE THREAD

**Issue by cuihaoleo** [languagetool-org/languagetool-website#9]
Text checking box in homepage is unusable in lastest Firefox and Chrome.

Firebug warning that there is a syntax error in the inline Javascript of the homepage.

I search the source and find it at /include/header.php:236 : 
```
	'ca'; 'Ignora l\'error d\'aquesta paraula',
```

It seems the ";" after string 'ca' should be a ':' .

**Comment by jaumeortola** [comment]
Sorry. It is solved now.
